# Generated by Django 3.0.7 on 2021-09-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.TextField()),
                ('theHash', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'url_shorten',
            },
        ),
    ]
